obj-y += board.o
lwl-y += lowlevel.o

pbl-y += lpddr4_pmu_train_1d_dmem.ddr-phy-fw.o
pbl-y += lpddr4_pmu_train_1d_imem.ddr-phy-fw.o
pbl-y += lpddr4_pmu_train_2d_dmem.ddr-phy-fw.o
pbl-y += lpddr4_pmu_train_2d_imem.ddr-phy-fw.o



