obj-y += board.o flash-header-niu.dcd.o
extra-y += flash-header-niu.dcd.S flash-header-niu.dcd
lwl-y += lowlevel.o

obj-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-niu-xload.dcd.o
extra-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-niu-xload.dcd.S flash-header-niu-xload.dcd
