obj-y += board.o flash-header-zodiac.dcd.o
extra-y += flash-header-zodiac.dcd.S flash-header-zodiac.dcd
lwl-y += lowlevel.o

obj-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-zodiac-xload.dcd.o
extra-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-zodiac-xload.dcd.S flash-header-zodiac-xload.dcd
